query shared {
  receivedProofs {
    id
    owner {
      did
    }
    verifier {
      did
    }
    data {
      id
      issuer {
        did
        username
      }
      fileName
      issuanceDate
      mimeType
      structured
      url
    }
  }
}
